=== VasavMittal/college-domain/college1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="helthcare">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="hospital" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="hid">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:pattern value="[0-9]"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="name">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="([a-zA-Z])*"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element type="xs:string" name="address"/>
              <xs:element  name="patientid">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="([a-zA-Z0-9])*"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element type="xs:string" name="doctorid"/>
              <xs:element type="xs:integer" name="inputid"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== VasavMittal/college-domain/college.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="college2.xsl" type="text/xsl"?>
<helthcare xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="college1.xsd">
	<hospital>
		<hid>1</hid>
		<name>Appolo</name>
		<address>Ludhiana</address>
		<patientid>null</patientid>
		<doctorid>null</doctorid>
		<inputid>1</inputid>
	</hospital>
	<hospital>
		<hid>1</hid>
		<name>Appolo</name>
		<address>Ludhiana</address>
		<patientid>1</patientid>
		<doctorid>null</doctorid>
		<inputid>2</inputid>
	</hospital>
	<hospital>
		<hid>1</hid>
		<name>Appolo</name>
		<address>Ludhiana</address>
		<patientid>1</patientid>
		<doctorid>1</doctorid>
		<inputid>3</inputid>
	</hospital>
	<hospital>
		<hid>1</hid>
		<name>Appolo</name>
		<address>Ludhiana</address>
		<patientid>2</patientid>
		<doctorid>null</doctorid>
		<inputid>3</inputid>
	</hospital>
	<hospital>
		<hid>1</hid>
		<name>Appolo</name>
		<address>Ludhiana</address>
		<patientid>2</patientid>
		<doctorid>1</doctorid>
		<inputid>4</inputid>
	</hospital>
</helthcare>
